# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    steps:
    - name: Create .env file
      run: echo -e "
        SERVER_PORT='10000'\n
        SECRET_SESSION_KEY='12345abcdef'\n
        CORS_ORIGIN='https://localhost:3000'\n
        DEV_DATABASE_USER='pguser'\n
        DEV_DATABASE_PASSWORD='pgpass'\n
        DEV_DATABASE_HOST='localhost'\n
        DEV_DATABASE_PORT='3003'\n
        DEV_DATABASE_NAME='pgdb'\n
        TEST_DATABASE_USER='pguser'\n
        TEST_DATABASE_PASSWORD='pgpass'\n
        TEST_DATABASE_HOST='localhost'\n
        TEST_DATABASE_PORT='3003'\n
        TEST_DATABASE_NAME='pgdb'\n
        PROD_DATABASE_USER=''\n
        PROD_DATABASE_PASSWORD=''\n
        PROD_DATABASE_HOST=''\n
        PROD_DATABASE_PORT='10'\n
        PROD_DATABASE_NAME=''" > .env
    - run: cat .env
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
