# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    steps:
    - name: Create .env file
      run: echo "SERVER_PORT=10000\nSECRET_SESSION_KEY='12345abcdef'\nCORS_ORIGIN='https://localhost:3000'\nDEV_DATABASE_USER='pguser'\nDEV_DATABASE_PASSWORD='pgpass'\nDEV_DATABASE_HOST='localhost'\nDEV_DATABASE_PORT=3003\nDEV_DATABASE_NAME='pgdb'\nTEST_DATABASE_USER='pguser'\nTEST_DATABASE_PASSWORD='pgpass'\nTEST_DATABASE_HOST='localhost'\nTEST_DATABASE_PORT=3003\nTEST_DATABASE_NAME='pgdb'\nPROD_DATABASE_USER=''\nPROD_DATABASE_PASSWORD=''\nPROD_DATABASE_HOST=''\nPROD_DATABASE_PORT=10\nPROD_DATABASE_NAME=''" > .env
    - run: cat .env
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
