# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2.0.2
      with:
        envkey_SERVER_PORT: 10000
        envkey_SECRET_SESSION_KEY: '12345abcdef'
        envkey_CORS_ORIGIN: 'https://localhost:3000'
        envkey_DEV_DATABASE_USER: 'pguser'
        envkey_DEV_DATABASE_PASSWORD: 'pgpass'
        envkey_DEV_DATABASE_HOST: 'localhost'
        envkey_DEV_DATABASE_PORT: 3003
        envkey_DEV_DATABASE_NAME: 'pgdb'
        envkey_TEST_DATABASE_USER: 'pguser'
        envkey_TEST_DATABASE_PASSWORD: 'pgpass'
        envkey_TEST_DATABASE_HOST: 'localhost'
        envkey_TEST_DATABASE_PORT: 3003
        envkey_TEST_DATABASE_NAME: 'pgdb'
        envkey_PROD_DATABASE_USER: ''
        envkey_PROD_DATABASE_PASSWORD: ''
        envkey_PROD_DATABASE_HOST: ''
        envkey_PROD_DATABASE_PORT: 0
        envkey_PROD_DATABASE_NAME: ''

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
